[versions]
kotlin = "2.2.20"

resourceFactory = "1.3.1"
runTask = "2.3.1"
shadow = "9.0.2"

[libraries]
kotlinJvm = { group = "org.jetbrains.kotlin.jvm", name = "org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }

[plugins]
resourceFactory-paper = { id = "xyz.jpenilla.resource-factory-paper-convention", version.ref = "resourceFactory" }
runTask-paper = { id = "xyz.jpenilla.run-paper", version.ref = "runTask" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }